### ISSUE TITLE
Cmake cannot find OpenCL for HelloOpenCL.exe using vcpkg

### ISSUE THREAD

**Issue by Tyler799** [KhronosGroup/OpenCL-Guide#29]
I am trying to follow the getting-started guide here: https://github.com/KhronosGroup/OpenCL-Guide/blob/main/chapters/getting_started_windows.md

If I run the following command:

`cmake -A x64 -S . -B .\build -D CMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake`

(Couldn't use <VCPKGROOT because I don't know how to set that variable, the variable editor in Windows apparently isn't enough)

Then it still fails with the following error:

```
CMake Error at C:/src/vcpkg/installed/x64-windows/share/opencl/vcpkg-cmake-wrapper.cmake:1 (_find_package):
  Could not find a package configuration file provided by "OpenCL" with any
  of the following names:

    OpenCLConfig.cmake
    opencl-config.cmake
```

Those files don't exist anywhere on my system, I'm assuming because I installed openCL using vcpkg. 

[FindOpenCL's page is quite sparse](https://cmake.org/cmake/help/latest/module/FindOpenCL.html). Is there some kind of "hint" that I can use to tell it that it's really under `C:\src\vcpkg\installed\x64-windows\bin\OpenCL.dll`? I thought using vcpkg was supposed to eliminate this problem...

**Comment by Tyler799** [comment]
The solution is to remove CONFIG from the Cmakelists, now it works!

**Comment by starball5** [comment]
Related question on Stack Overflow: [How to get Cmake to find OpenCL if it was installed via vcpkg?](https://stackoverflow.com/q/76318281/11107541) (and [my answer post there](https://stackoverflow.com/a/76319709/11107541)). It'd be nice to find the root cause (I have no idea what it is).

**Comment by bashbaug** [comment]
Ping @MathiasMagnus - I think you had the vcpkg stuff working previously?

It's been a while since I've done this but it looks like I got something working through vcpkg while testing an old OpenCL-SDK PR: https://github.com/KhronosGroup/OpenCL-SDK/pull/37

This issue might also be relevant?  Not sure... I am clearly not a vcpkg expert!  https://github.com/KhronosGroup/OpenCL-SDK/issues/28

**Comment by MathiasMagnus** [comment]
@Tyler799 @starball5 @bashbaug There are a few things to patch up, all of which will be tackled shortly.

1. The vcpkg port doesn't wrap the OpenCL-SDK repo, because when I last tackled it, it wouldn't have simplified much in the port, because Vcpkg is [lacking the ability to clone with submodules](https://github.com/microsoft/vcpkg/issues/24521). It is when one installs the OpenCL-SDK superproject that `CONFIG` support works. `find_package(OpenCL CONFIG)` is a Khronos OpenCL-SDK thing (until Linux distros or vendor SDKs don't pick up this interface). Until the Vcpkg port doesn't wrap the OpenCL-SDK explicitly and continues to assemble the components one-by-one, Vcpkg won't work with `CONFIG`.
2. `COMPONENTS` for the moment is a `CONFIG`-only feature, but that is to change shortly. I'm in the [final stages](https://github.com/MathiasMagnus/Test-FindOpenCL/pull/1) of testing my contribution to Kitware's `FindOpenCL.cmake` which will add component support to the `MODULE`-mode search syntax. (I'm stuck on include path issues on MacOS with XCode only.)

Once both of these are implemented (and likely both are going to land sometime during the summer), it will not matter which syntax you use to consume OpenCL from Vcpkg and whether you use components in MODULE or COMPONENT mode.
